name: Unity Continuous Integration Workflow

on:
  push:
    branches:
      - main

jobs:
  common_steps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.4.0
        with:
          lfs: true

      - name: Cache Unity Library
        uses: actions/cache@v2
        with:
          path: |
            ${{ github.workspace }}/Library
            ${{ github.workspace }}/Assets
            ${{ github.workspace }}/ProjectSettings
          key: Library-${{ runner.os }}-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            Library-${{ runner.os }}-

  unity_tests:
    needs: common_steps
    runs-on: ubuntu-latest
    env:
      projectPath: EngineeringThesis

    steps:
      - name: Copy Unity to temporary folder
        run: |
          folderName=$(echo "${PWD##*/}")
          rsync -r "$GITHUB_WORKSPACE" "copiedProject" 
          ls -F "copiedProject/$folderName"
      
      - name: Run Unity Tests
        id: runUnityTests
        uses: game-ci/unity-test-runner@v3
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          projectPath: ./copiedProject/${{ env.projectPath }}
          testMode: all
          coverageOptions: 'generateAdditionalMetrics;generateHtmlReport;generateBadgeReport'

      - name: Upload Test Coverage Results
        uses: actions/upload-artifact@v2
        with:
          name: Test Coverage Results (all)
          path: ${{ steps.runUnityTests.outputs.coveragePath }}

  unity_build:
    needs: common_steps
    strategy:
      matrix:
          targetPlatform:
          #- StandaloneOSX # Build a macOS standalone (Intel 64-bit).
          #- StandaloneWindows # Build a Windows standalone.
          #- StandaloneWindows64 # Build a Windows 64-bit standalone.
          #- StandaloneLinux64 # Build a Linux 64-bit standalone.
          #- iOS # Build an iOS player.
          - Android # Build an Android .apk standalone app.
          #- WebGL # WebGL.

    runs-on: ubuntu-latest

    steps:
      - name: Build Unity Project
        uses: game-ci/unity-builder@v3
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}

      - name: Upload Unity Build
        uses: actions/upload-artifact@v2
        with:
          name: Unity Build-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}
